/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-05-17 06:05:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pharmacystore.pojo.Category;
import java.util.List;
import com.pharmacystore.daoimpl.CategoryDaoImpl;
import com.pharmacystore.dao.CategoryDao;

public final class additemtoproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pharmacystore.daoimpl.CategoryDaoImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pharmacystore.dao.CategoryDao");
    _jspx_imports_classes.add("com.pharmacystore.pojo.Category");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav{\r\n");
      out.write("background-color:#1977cc;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function validateprodid(productid) \r\n");
      out.write("{\r\n");
      out.write("    \r\n");
      out.write("    var numval = productid.value\r\n");
      out.write("    \r\n");
      out.write("    curprodvar = numval.replace(/[\\\\A-Za-z!\"Â£$%^&\\,*+_={};:'@#~,.Å \\/<>?|`Â¬\\]\\[]/g,'');\r\n");
      out.write("    productid.value =  curprodvar;\r\n");
      out.write("    \r\n");
      out.write("    productid.focus;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validatecatid(categoryid); \r\n");
      out.write("{\r\n");
      out.write("    \r\n");
      out.write("    var numval = categoryid.value\r\n");
      out.write("    \r\n");
      out.write("    curprodvar = numval.replace(/[\\\\A-Za-z!\"Â£$%^&\\,*+_={};:'@#~,.Å \\/<>?|`Â¬\\]\\[]/g,'');\r\n");
      out.write("    categoryid.value =  curprodvar;\r\n");
      out.write("    \r\n");
      out.write("    categoryid.focus;\r\n");
      out.write("}\r\n");
      out.write("function validatequantity(quantity); \r\n");
      out.write("{\r\n");
      out.write("    \r\n");
      out.write("    var numval = quantity.value\r\n");
      out.write("    \r\n");
      out.write("    curprodvar = numval.replace(/[\\\\A-Za-z!\"Â£$%^&\\,*+_={};:'@#~,.Å \\/<>?|`Â¬\\]\\[]/g,'');\r\n");
      out.write("    quantity.value =  curprodvar;\r\n");
      out.write("    \r\n");
      out.write("    quantity.focus;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");

if(!session.isNew() || session.getAttribute("ADMIN") != null){
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<nav class=\"navbar navbar-default\" id=\"nav\">\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<div class=\"navbar-header\">\r\n");
      out.write("						<a href=\"adminhome.jsp\" class=\"navbar-brand\" id=\"nav\"> ADMIN HOME </a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("						<li><a href=\"logoutadmin.jsp\" id=\"nav\"><span class=\"glyphicon glyphicon-log-out\" id=\"nav\"></span> Logout</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-2\"></div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                \r\n");
      out.write("                <form action=\"addproduct.jsp\" method=\"post\" id=\"fileForm\" role=\"form\">\r\n");
      out.write("                <fieldset><legend class=\"text-center\">All Fields <span class=\"req\"><small> required *</small></span></legend>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"productname\"><span class=\"req\">* </span> Product Name </label>\r\n");
      out.write("                        <input required name=\"productname\" type=\"text\" class=\"form-control inputpass\" minlength=\"4\" maxlength=\"30\"  id=\"productname\" /> </p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    				<div class=\"form-group\">	\r\n");
      out.write("                        <label for=\"categoryid\"><span class=\"req\">* </span> Category Name </label>\r\n");
      out.write("	                        <select class=\"form-control\" id=\"categoryid\" name=\"categoryid\">\r\n");
      out.write("	        					");

	        						CategoryDao daoImpl = new CategoryDaoImpl();
                        			List<Category> lst = daoImpl.getAllCategories();
                        			if(lst.size() > 0)
                        			{
                        				for(Category category : lst)
                        				{
                        		
      out.write("\r\n");
      out.write("                        				<option value=\"");
      out.print(category.getCategoryId());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(category.getCategoryName());
      out.write("</option>\r\n");
      out.write("                        		");
			
                        				}
                        			}
	        					
      out.write("\r\n");
      out.write("	      					</select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"price\"><span class=\"req\">* </span> Price </label> \r\n");
      out.write("                            <input class=\"form-control\" required type=\"text\" name=\"price\" id = \"price\" />   \r\n");
      out.write("                                <div class=\"status\" id=\"status\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"quantity\"><span class=\"req\">* </span>Quantity </label>\r\n");
      out.write("                        <input required type=\"text\" name=\"quantity\" id=\"quantity\" class=\"form-control\" max=\"60\" min=\"18\" onkeyup=\"validatequantity(this);\" placeholder=\"Enter quantity to add\"/> \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"description\"><span class=\"req\">* </span> Description </label>\r\n");
      out.write("                        <textarea required name=\"description\" id=\"description\" class=\"form-control\" maxlength=\"150\"  placeholder=\"Description\"\r\n");
      out.write("                        rows=\"3\" cols = \"30\" maxlength=\"100\"></textarea> \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("    \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"btn btn-success\" type=\"submit\" name=\"submit_reg\" value=\"Submit Product\">\r\n");
      out.write("                </div>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("           </form>\r\n");
      out.write("                 </div>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
 
}else
{
	
      out.write("\r\n");
      out.write("	<p style=\"color:red\">You need to login first to add product</p>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminlogin.html", out, false);
      out.write('\r');
      out.write('\n');
 
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
