/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-05-17 06:05:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pharmacystore.pojo.Product;
import java.util.List;
import com.pharmacystore.daoimpl.ProductDaoImpl;
import com.pharmacystore.dao.ProductDao;

public final class viewallproductsadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pharmacystore.dao.ProductDao");
    _jspx_imports_classes.add("com.pharmacystore.pojo.Product");
    _jspx_imports_classes.add("com.pharmacystore.daoimpl.ProductDaoImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>View All Product</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("	display: none; /* Hidden by default */\r\n");
      out.write("	position: fixed; /* Stay in place */\r\n");
      out.write("	z-index: 1; /* Sit on top */\r\n");
      out.write("	padding-top: 100px; /* Location of the box */\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	width: 100%; /* Full width */\r\n");
      out.write("	height: 100%; /* Full height */\r\n");
      out.write("	overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("	background-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content */\r\n");
      out.write(".modal-content {\r\n");
      out.write("	background-color: #fefefe;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border: 1px solid #888;\r\n");
      out.write("	width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Close Button */\r\n");
      out.write(".close {\r\n");
      out.write("	color: #aaaaaa;\r\n");
      out.write("	float: right;\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover, .close:focus {\r\n");
      out.write("	color: #000;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#nav{\r\n");
      out.write("background-color:#1977cc;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myBtn:hover{\r\n");
      out.write("background-color:#1997cc;\r\n");
      out.write("}\r\n");
      out.write("#myBtn2:hover{\r\n");
      out.write("background-color:#1997cc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	if(!session.isNew() || session.getAttribute("ADMIN") != null)
	{
	
      out.write("\r\n");
      out.write("			<nav class=\"navbar navbar-default\">\r\n");
      out.write("				<div class=\"container-fluid\" id=\"nav\">\r\n");
      out.write("					<div class=\"navbar-header\">\r\n");
      out.write("					<a href=\"adminhome.jsp\" class=\"navbar-brand\" id=\"nav\"> ADMIN HOME </a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("					<li><a href=\"logoutadmin.jsp\"id=\"nav\"><span class=\"glyphicon glyphicon-log-out\" id=\"nav\"></span> Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("		 	<div class=\"table-wrapper\">\r\n");
      out.write("            	<div class=\"table-title\">\r\n");
      out.write("                	<div class=\"row\">\r\n");
      out.write("                    	<div class=\"col-sm-6\">\r\n");
      out.write("                        	<h2> Products For You</h2><br>\r\n");
      out.write("                    	</div>\r\n");
      out.write("                	</div>\r\n");
      out.write("            	</div>\r\n");
      out.write("            <table class=\"table table-striped table-hover table-bordered\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Product ID</th>\r\n");
      out.write("                        <th> Product Name</th>\r\n");
      out.write("                        <th>Category id</th>\r\n");
      out.write("                        <th>Quantity</th>\r\n");
      out.write("                        <th> Price</th>\r\n");
      out.write("                        <th>Description</th>\r\n");
      out.write("                        \r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");


                    ProductDao daoImpl = new ProductDaoImpl();
                    
                   List<Product> lst = 
                		   daoImpl.getAllProducts();

                    if(lst.size() > 0)
                    {
                    for (Product p : lst) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td>");
      out.print(p.getProductid());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                        <td>");
      out.print(p.getProductname());
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
      out.print(p.getCategoryid());
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
      out.print(p.getQuantity());
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>");
      out.print(p.getPrice());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(p.getDescription());
      out.write("</td>\r\n");
      out.write("                        \r\n");
      out.write("                         <td>\r\n");
      out.write("                            <form action=\"DeleteProduct.jsp\" method=\"post\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"productid\" value=\"");
      out.print(p.getProductid());
      out.write("\"/>\r\n");
      out.write("                            <input class = \"btn btn-danger\" id=\"myBtn2\" type=\"submit\" value=\"Delete This Product\"/>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        \r\n");
      out.write("                        <td>\r\n");
      out.write("                        	<button id=\"myBtn\" class=\"btn btn-danger\"\r\n");
      out.write("                        	onclick=\"openMyDialog(");
      out.print(p.getProductid());
      out.write(")\">Update This Product</button>\r\n");
      out.write("                        </td>  \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                     \r\n");
      out.write("                        \r\n");
      out.write("                                             \r\n");
      out.write("                   </tr>\r\n");
      out.write("                ");
}}
				
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("         </div>\r\n");
      out.write("		<div class=\"clearfix\">\r\n");
      out.write("                <ul class=\"pagination\">\r\n");
      out.write("                    <li class=\"page-item disabled\"><a href=\"#\">Previous</a></li>\r\n");
      out.write("                    <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">1</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>\r\n");
      out.write("                    <li class=\"page-item \"><a href=\"#\" class=\"page-link\">3</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">4</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">Next</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!-- Start Of The Modal Design-->\r\n");
      out.write("<div class=\"container\" align=\"center\">\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\">&times;</span>\r\n");
      out.write("    <table class=\"table table-hover\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th align=\"center\"> <b>Enter Product Details To Be Updated : </b></th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            	<label class=\"control-label\" for=\"pname\">Enter New Name</label> \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"pname\" name=\"pname\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            	<label class=\"control-label\" for=\"price\">Enter New Price</label> \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"price\" name=\"price\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            	<label class=\"control-label\" for=\"quantity\">Enter New Quantity</label> \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"quantity\" name=\"quantity\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            	<label class=\"control-label\" for=\"pdesc\">Enter New Description</label> \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"pdesc\" name=\"pdesc\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><button id=\"btnUpdate\" class=\"btn btn-danger\" onclick=\"updateProduct()\">\r\n");
      out.write("            		Update Product\r\n");
      out.write("            	</button>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Of The Modal Design-->\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("									// Get the modal\r\n");
      out.write("									var modal = document\r\n");
      out.write("											.getElementById(\"myModal\");\r\n");
      out.write("\r\n");
      out.write("									// Get the button that posts complaint\r\n");
      out.write("									var btnRaise = document\r\n");
      out.write("											.getElementById(\"btnRaise\");\r\n");
      out.write("\r\n");
      out.write("									// Get the <span> element that closes the modal\r\n");
      out.write("									var span = document\r\n");
      out.write("											.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("									var productid = 0;\r\n");
      out.write("\r\n");
      out.write("									// When the user clicks the button, open the modal \r\n");
      out.write("									function openMyDialog(id) {\r\n");
      out.write("										modal.style.display = \"block\";\r\n");
      out.write("										productid = id;\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									function updateProduct() {\r\n");
      out.write("\r\n");
      out.write("										var price = document\r\n");
      out.write("												.getElementById(\"price\").value;\r\n");
      out.write("										\r\n");
      out.write("										var qty = document\r\n");
      out.write("										.getElementById(\"quantity\").value;\r\n");
      out.write("	\r\n");
      out.write("										var pname = document\r\n");
      out.write("										.getElementById(\"pname\").value;\r\n");
      out.write("										\r\n");
      out.write("										var pdesc = document\r\n");
      out.write("										.getElementById(\"pdesc\").value;\r\n");
      out.write("										\r\n");
      out.write("										var url = \"UpdateProduct.jsp?productid=\"\r\n");
      out.write("												+ productid\r\n");
      out.write("												+ \"&price=\"\r\n");
      out.write("												+ price\r\n");
      out.write("												+ \"&qty=\"\r\n");
      out.write("												+ qty\r\n");
      out.write("												+ \"&pname=\"\r\n");
      out.write("												+ pname\r\n");
      out.write("												+ \"&pdesc=\"\r\n");
      out.write("												+ pdesc;\r\n");
      out.write("\r\n");
      out.write("										modal.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("										if (window.XMLHttpRequest) {\r\n");
      out.write("											request = new XMLHttpRequest();\r\n");
      out.write("										} else if (window.ActiveXObject) {\r\n");
      out.write("											request = new ActiveXObject(\r\n");
      out.write("													\"Microsoft.XMLHTTP\");\r\n");
      out.write("										}\r\n");
      out.write("\r\n");
      out.write("										try {\r\n");
      out.write("											request.onreadystatechange = getProductResponse;\r\n");
      out.write("											request.open(\"GET\", url, true);\r\n");
      out.write("											request.send();\r\n");
      out.write("										} catch (e) {\r\n");
      out.write("											alert(\"Unable to connect to server\");\r\n");
      out.write("										}\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									function getProductResponse() {\r\n");
      out.write("										if (request.readyState == 4) {\r\n");
      out.write("											var val = request.responseText;\r\n");
      out.write("											if (val.trim() == \"success\") {\r\n");
      out.write("												alert(\"product updated\");\r\n");
      out.write("												window.location.reload(true);\r\n");
      out.write("											} else {\r\n");
      out.write("												alert(\"product update failed\");\r\n");
      out.write("											}\r\n");
      out.write("										}\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									// When the user clicks on <span> (x), close the modal\r\n");
      out.write("									span.onclick = function() {\r\n");
      out.write("										modal.style.display = \"none\";\r\n");
      out.write("										alert(productid);\r\n");
      out.write("									}\r\n");
      out.write("\r\n");
      out.write("									// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("									window.onclick = function(event) {\r\n");
      out.write("										if (event.target == modal) {\r\n");
      out.write("											modal.style.display = \"none\";\r\n");
      out.write("										}\r\n");
      out.write("									}\r\n");
      out.write("								</script>\r\n");
      out.write("		");

				
			}
			else{
		
      out.write("\r\n");
      out.write("			<p style=color:red> You need to login first !!! </p>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "adminlogin.html", out, false);
      out.write("\r\n");
      out.write("		");
				
			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
